pipeline{
    agent any
    stages{
        stage("Deploy") {
            environment {
                DOCKER_PASS = credentials("docker_token")
            }
            steps {
                    bat 'docker build -t huyfst/proxy .'
                    bat 'docker login -u huyfst -p %DOCKER_PASS%'
                    bat 'docker push huyfst/proxy'
                    bat 'trivy image huyfst/proxy'
            }
        }
    }
}