pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                bat 'npm install jest'
                bat 'npm run test'
            }
        }
        stage('Sonar scan') {
            environment {
                scannerHome = tool 'sonarscan'
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    bat "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('Deploy') {
            environment {
                DOCKER_PASS = credentials("docker_token")
            }
            steps {
                bat 'docker build -t huyfst/order .'
                bat 'docker login -u huyfst -p %DOCKER_PASS%'
                bat 'docker push huyfst/order'
                bat 'trivy image huyfst/order'
            }
        }
    }
}

