pipeline{
    agent any

    stages{
        stage("Test") {
            steps {
                dir('payment') {
                    bat "go test ./tests"
                }
            }
        }
        stage('Sonar scan') {
            environment {
                scannerHome = tool 'sonarscan'
            }
            steps {
                dir('payment') {
                    withSonarQubeEnv('sonarqube') {
                        bat "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }
        stage("Deploy") {
            environment {
                DOCKER_PASS = credentials("docker_token")
            }
            steps {
                dir('payment') {
                    bat 'docker build -t huyfst/payment .'
                    bat 'docker login -u huyfst -p %DOCKER_PASS%'
                    bat 'docker push huyfst/payment'
                    bat 'trivy image huyfst/payment'
                }
            }
        }
    }
}