pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                dir('product') {
                    bat 'npm install jest'
                    bat 'npm run test'  
                }
            }
        }
        // stage('Sonar scan') {
        //     environment {
        //         scannerHome = tool 'sonarscan'
        //     }
        //     steps {
        //         dir('product') {
        //             withSonarQubeEnv('sonarqube') {
        //                 bat "${scannerHome}/bin/sonar-scanner"
        //             }
        //         }
        //     }
        // }
        stage('Deploy') {
            environment {
                DOCKER_PASS = credentials("docker_token")
            }
            steps {
                dir('product') {
                    bat 'docker build -t huyfst/product .'
                    bat 'docker login -u huyfst -p %DOCKER_PASS%'
                    bat 'docker push huyfst/product'
                    bat 'trivy image huyfst/product'
                }
            }
        }
    }
}

